### ISSUE TITLE
ELB endpoint can't connect (NonRecoverableError)

### ISSUE THREAD

**Issue by joshuap-cfy** [cloudify-incubator/cloudify-boto3-plugin#83]
M7 Issue: (priority 2) NonRecoverableError: Cannot connect to ELB endpoint
Symptom:

The ELB (which is the ELB implemented in Boto3_plugin) is created successfully but the workflow fails at the task to connect an EC2 instance to the ELB.

Steps to reproduce:
I’m using aws_1.4.11 and M7 in the test.
1. Deploy the attached blueprint
2. Notice the “[Broker1_244922->Broker1Elb_m3vudb|establish] Task failed
2017-06-21T00:53:13 CFY <broker1620m> [Broker1_244922->Broker1Elb_m3vudb|establish] Task failed 'cloudify_aws.ec2.elasticloadbalancer.associate' -> Cannot connect to ELB endpoint. You must either provide elb_region_name or both elb_region_name and elb_region_endpoint.
Traceback (most recent call last):
File "/tmp/pip-build-TeHrVQ/cloudify-plugins-common/cloudify/dispatch.py", line 600, in main
File "/tmp/pip-build-TeHrVQ/cloudify-plugins-common/cloudify/dispatch.py", line 366, in handle
File "/opt/mgmtworker/env/plugins/cloudify-aws-plugin-1.4.11/lib/python2.7/site-packages/cloudify_aws/ec2/elasticloadbalancer.py", line 51, in associate
return ElbInstanceConnection().associate_helper(args)
File "/opt/mgmtworker/env/plugins/cloudify-aws-plugin-1.4.11/lib/python2.7/site-packages/cloudify_aws/ec2/elasticloadbalancer.py", line 62, in _init_
self.client = client or connection.ELBConnectionClient().client()
File "/opt/mgmtworker/env/plugins/cloudify-aws-plugin-1.4.11/lib/python2.7/site-packages/cloudify_aws/connection.py", line 176, in client
'Cannot connect to ELB endpoint. '
NonRecoverableError: Cannot connect to ELB endpoint. You must either provide elb_region_name or both elb_region_name and elb_region_endpoint.

**Comment by EarthmanT** [comment]
resolved with blueprint example.
